'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wfPage3
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''rblSexualAssaultPriorReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblSexualAssaultPriorReport As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''cbMensusAssault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMensusAssault As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbUrinated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbUrinated As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''rblSexualAssaultAfterReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblSexualAssaultAfterReport As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''cbRemovedTampon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbRemovedTampon As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbDeficated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDeficated As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''rblWasItReported control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblWasItReported As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''cbInsertedTampon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbInsertedTampon As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbDouched control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDouched As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''rblSexBeforeReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblSexBeforeReport As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''cbChangedClothes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbChangedClothes As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbBrushedTeeth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbBrushedTeeth As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''rblSexAfterReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblSexAfterReport As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''cbBathed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbBathed As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbAte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbAte As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''rblBirthControlMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblBirthControlMethod As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''cbShowered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbShowered As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbDrank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDrank As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''rblGPAB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblGPAB As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''cbWashed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbWashed As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cbSmoked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSmoked As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''rbAssailantInjured control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbAssailantInjured As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtAssailantInjured control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAssailantInjured As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RadioButtonList1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonList1 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''TextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbWeapons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbWeapons As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtWeapons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeapons As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbPhysicalForce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPhysicalForce As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtPhysicalForce control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhysicalForce As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbStrangulation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbStrangulation As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtStrangulation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStrangulation As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbLossConsciousness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLossConsciousness As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtLossConsciousness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLossConsciousness As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbThreatHarm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbThreatHarm As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtThreatHarm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtThreatHarm As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbInjuriesInflicted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbInjuriesInflicted As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtInjuriesInflicted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInjuriesInflicted As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbBindingOrRestraint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbBindingOrRestraint As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtBindingOrRestraint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBindingOrRestraint As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbKnowGangAffiliations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbKnowGangAffiliations As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtKnowGangAffiliations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKnowGangAffiliations As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbOther As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOther As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbIngestionDrugs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbIngestionDrugs As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtIngestionDrugs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIngestionDrugs As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbIngestionAlcohol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbIngestionAlcohol As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtIngestionAlcohol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIngestionAlcohol As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPriorIncident control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPriorIncident As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateTime As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbDifferentSymptoms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbDifferentSymptoms As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtDifferentSymptoms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDifferentSymptoms As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLastMemory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLastMemory As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNextMemory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNextMemory As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbLossConsciousness2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLossConsciousness2 As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtLossConsciousness2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLossConsciousness2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAproximateLengthOfTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAproximateLengthOfTime As Global.System.Web.UI.WebControls.TextBox
End Class
