'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wfPage1
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''txtLawEnforcementAgency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLawEnforcementAgency As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAgencyCase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAgencyCase As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhone As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAgencyAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAgencyAddress As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPrintName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrintName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSignature As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtChildProtectiveService control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChildProtectiveService As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtChildProtectiveServiceAgencyCase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChildProtectiveServiceAgencyCase As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtChildProtectiveServicePhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChildProtectiveServicePhone As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtChildProtectiveServiceAgencyAdress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChildProtectiveServiceAgencyAdress As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtChildProtectiveServicePrintName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChildProtectiveServicePrintName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtChildProtectiveServiceSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChildProtectiveServiceSignature As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtChildProtectiveServiceDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChildProtectiveServiceDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCrisisCenterCacAdvocate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCrisisCenterCacAdvocate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCrisisCenterCacAdvocateName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCrisisCenterCacAdvocateName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtCrisisCenterCacAdvocatePhone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCrisisCenterCacAdvocatePhone As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtForensicExaminerSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForensicExaminerSignature As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtForensicExaminerDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForensicExaminerDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtForensicExaminerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForensicExaminerName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtForensicExaminerNameSignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForensicExaminerNameSignature As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtForensicExaminerNameDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtForensicExaminerNameDate As Global.System.Web.UI.WebControls.TextBox
End Class
