'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wfPage2
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''txtPatientHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPatientHistory As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rblVaginalContactPenis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblVaginalContactPenis As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rblVaginalContactFinger control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblVaginalContactFinger As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rblVaginalContactObject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblVaginalContactObject As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rblVaginalContactObjectDescribe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblVaginalContactObjectDescribe As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rblAnalContactPenis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblAnalContactPenis As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rblAnalContactFinger control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblAnalContactFinger As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rblAnalContactObject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblAnalContactObject As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rblAnalContactObjectDescribe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblAnalContactObjectDescribe As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rblOralGenitalsPatientByAssailant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblOralGenitalsPatientByAssailant As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rblOralGenitalsAssailantByPatient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblOralGenitalsAssailantByPatient As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtPatientHistoryInformant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPatientHistoryInformant As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rblOralAnusPatientByAssailant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblOralAnusPatientByAssailant As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtRelationshipTopatient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRelationshipTopatient As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rblOralAnusAssailantByPatient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblOralAnusAssailantByPatient As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtPresentinProblem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPresentinProblem As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rblMasturbationPatientByAssailant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblMasturbationPatientByAssailant As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rblMasturbationAssailantByPatient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblMasturbationAssailantByPatient As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtMasturbationOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMasturbationOther As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rblMasturbationEjaculation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblMasturbationEjaculation As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rblMasturbationEjaculationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblMasturbationEjaculationType As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtMasturbationEjaculationTypeOther control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMasturbationEjaculationTypeOther As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rblMasturbationBirthControlMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblMasturbationBirthControlMethod As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rblMasturbationLubricant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblMasturbationLubricant As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtMasturbationLubricantKind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMasturbationLubricantKind As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rblMasturbationLossOfConsciousness control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblMasturbationLossOfConsciousness As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''rblMasturbationFondling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblMasturbationFondling As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''TextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rblMasturbationMenstrating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblMasturbationMenstrating As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtPostAssaultIdentityAssailant1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostAssaultIdentityAssailant1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPostAssaultAge1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostAssaultAge1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPostAssaultSex1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostAssaultSex1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPostAssaultRace1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostAssaultRace1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPostAssaultRelationship1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostAssaultRelationship1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPostAssaultCondom1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostAssaultCondom1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPostAssaultIdentityAssailant2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostAssaultIdentityAssailant2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPostAssaultAge2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostAssaultAge2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPostAssaultSex2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostAssaultSex2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPostAssaultRace2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostAssaultRace2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPostAssaultRelationship2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostAssaultRelationship2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPostAssaultCondom2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostAssaultCondom2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPostAssaultIdentityAssailant3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostAssaultIdentityAssailant3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPostAssaultAge3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostAssaultAge3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPostAssaultSex3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostAssaultSex3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPostAssaultRace3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostAssaultRace3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPostAssaultRelationship3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostAssaultRelationship3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPostAssaultCondom3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostAssaultCondom3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rblHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblHours As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''txtDateAssault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDateAssault As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTimeAssault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTimeAssault As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLocationAssault control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLocationAssault As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtOnset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOnset As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMostRecent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMostRecent As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtNumAssailants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumAssailants As Global.System.Web.UI.WebControls.TextBox
End Class
